### ISSUE TITLE
Use google placeId

### ISSUE THREAD

**Issue by theimpostor** [n00rsy/halal-map#1]
Nice work!

Consider retrieving and saving the google maps placeId, then you can link to the google maps listing directly (to see reviews, photos, navigate, etc): https://developers.google.com/maps/documentation/places/web-service/place-id

https://github.com/n00rsy/halal-map/blob/97b87326976e57caab7918ad9f232a9c6b201fad/geocoder.py#L31

**Comment by n00rsy** [comment]
great suggestion! Implemented via 3be60a1a239976e079cbf51d3f32717eba5dc6d2
